---
title: "bffs_neuralsim_bayesian_analyses_04032026"
output:
  pdf_document: default
  html_document: default
date: "2026-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (!("pacman" %in% installed.packages()[,])) {
    install.packages("pacman")
  }
pacman::p_load(tidyverse, mice, lmerTest, brms, sjPlot)
```


```{r}
project_path <- "C:/Users/avallora/Box/F32/neuralsimilarity/neural_similarity" 

# QST data
qst_df <- read.csv(file.path(project_path,
                             "/for_analysis/bffs_questionnaires_01192024.csv", 
                             fsep = ""), stringsAsFactors = TRUE) |>
  # Adjust reported ethnicity
  mutate(ethnicity = recode(ethnicity, `Another ethnicity` = "Another ethnicity", 
                            `Hispanic/Latino/Latina/Latinx` = "Hispanic/Latino/Latina/Latinx", 
                            `Hispanic/Latino/Latina/Latinx, Non-Hispanic` =
                              "Hispanic/Latino/Latina/Latinx", 
                            `Non-Hispanic` = "Non-Hispanic", 
                            `Non-Hispanic, Unknown` = "Non-Hispanic",
                            `Unknown` = "Unknown"))

# Neural sim synchrony data
synchrony_df <- read.csv(file.path(project_path,
                             "/for_analysis/neural_similarity_ratings_allregions_data_11212024.csv", 
                             fsep = ""), stringsAsFactors = FALSE) |>
   mutate(neuralSimConditionCodes = as.factor(recode(neuralSimCondition,
                                                    "classic" = 0,
                                                    "self_perspective" = 1,
                                                    "friend_perspective" = 2)),
          atlasNameCodes = as.factor(recode(atlasName, "dmPFC" = 0, "vmPFC" = 1,
                                                       "rTPJ" = 2, "lTPJ" = 3))) |>
  # Disambigulate within and between variance
  group_by(dyad) |>
  mutate(traitRatings = mean(ratingsSim, na.rm = TRUE),
         stateRatings = ratingsSim - traitRatings) |>
  ungroup() |>
  left_join(qst_df) |>
  mutate(saTotalC = as.numeric(scale(saTotal, center = TRUE, scale = FALSE))) |>
  select(dyad, id, saTotal, saTotalC, atlasName, atlasNameCodes, clip, ratingsSim, 
         traitRatings, stateRatings, neuralSimCondition, neuralSimConditionCodes, 
         deconMeanCor, siOverallVisit1, siOverallVisit2, raRespondentAffection, 
         uncomfortableWatchingSelf) |>
  filter(!is.na(deconMeanCor))


# included ids
included_ids <- synchrony_df |> select(id) |> unique() |> left_join(qst_df)
```


## Multiple imputation
```{r}
# All data
imputed_df <- mice(synchrony_df, m = 25, maxit = 50, method = 'pmm', 
                   seed = 500, print = FALSE)

# Split imputed data for region analyses
imputed_datasets <- lapply(1:25, function(i) complete(imputed_df, i))

split_datasets <- lapply(imputed_datasets, function(df) {
  split(df, df$atlasName) 
})

combine_splits <- function(group_name) {
  lapply(split_datasets, function(group_list) group_list[[group_name]])
}

dmPFC_data <- combine_splits("dmPFC")
vmPFC_data <- combine_splits("vmPFC")
rTPJ_data <- combine_splits("rTPJ")
lTPJ_data <- combine_splits("lTPJ")


# dmPFC & rTPJ
dmPFC_rTPJ_data <- lapply(imputed_datasets, function(df) {
  df[df$atlasName %in% c("dmPFC", "rTPJ"), ] 
})

# vmPFC & lTPJ
vmPFC_lTPJ_data <- lapply(imputed_datasets, function(df) {
  df[df$atlasName %in% c("vmPFC", "lTPJ"), ] 
})

# dmPFC, vmPFD and rTPJ
dmPFC_vmPFC_rTPJ_data <- lapply(imputed_datasets, function(df) {
  df[df$atlasName %in% c("dmPFC", "vmPFC", "rTPJ"), ] 
})
```


# bayesian models
## Matches mlm1i
```{r}
#plan(multisession, workers = 2)

fit1 <- brm_multiple(
        deconMeanCor ~ traitRatings + atlasNameCodes +
                  stateRatings*neuralSimConditionCodes*saTotalC +
                  (1|dyad), 
        data = imputed_df, 
        seed = 111, 
        iter = 8000,
        warmup = 1000,
        chains = 4,
        cores = 2)
```

```{r}
summary(fit1)

tab_model(fit1, digits = 3, show.se = TRUE, show.stat = TRUE, show.ci = TRUE)
```


## Matches mlm2i
```{r}
fit2 <- brm_multiple(
        deconMeanCor ~ traitRatings + atlasNameCodes +
                  stateRatings*neuralSimConditionCodes +
                  (1|dyad), 
        data = imputed_df, 
        seed = 111, 
        iter = 8000,
        warmup = 1000,
        chains = 4,
        cores = 2)
```


```{r}
summary(fit2)
```


## Matches mlm3i
```{r}
fit3 <- brm_multiple(
        deconMeanCor ~ atlasNameCodes*neuralSimConditionCodes + (1|dyad), 
        data = imputed_df, 
        seed = 111, 
        iter = 8000,
        warmup = 1000,
        chains = 4,
        cores = 2)
```


```{r}
summary(fit3)
```


## Matches dmpfc - stateRatings:neuralSimConditionCodes1
```{r}
fit4 <- brm_multiple(
        deconMeanCor ~ traitRatings + 
                       stateRatings*neuralSimConditionCodes + (1 | dyad), 
        data = dmPFC_data, 
        seed = 111, 
        iter = 8000,
        warmup = 1000,
        chains = 4,
        cores = 2)
```


```{r}
summary(fit4)
```


## Matches # vmpfc - stateRatings:neuralSimConditionCodes1
```{r}
fit5 <- brm_multiple(
        deconMeanCor ~ traitRatings + 
                       stateRatings*neuralSimConditionCodes + (1 | dyad), 
        data = vmPFC_data, 
        seed = 111, 
        iter = 8000,
        warmup = 1000,
        chains = 4,
        cores = 2)
```


```{r}
summary(fit5)
```


## Matches ltpj
```{r}
fit6 <- brm_multiple(
        deconMeanCor ~ traitRatings + 
                       stateRatings*neuralSimConditionCodes + (1 | dyad), 
        data = lTPJ_data, 
        seed = 111, 
        iter = 8000,
        warmup = 1000,
        chains = 4,
        cores = 2)
```


```{r}
summary(fit6)
```

## Matches rtpj
```{r}
fit7 <- brm_multiple(
        deconMeanCor ~ traitRatings + 
                       stateRatings*neuralSimConditionCodes + (1 | dyad), 
        data = rTPJ_data, 
        seed = 111, 
        iter = 8000,
        warmup = 1000,
        chains = 4,
        cores = 2)
```


```{r}
summary(fit7)
```

dmpfc with social anxiety
```{r}
fit8 <- brm_multiple(
        deconMeanCor ~ traitRatings +
                       stateRatings*neuralSimConditionCodes*saTotalC + (1 | dyad), 
        data = dmPFC_data, 
        seed = 111, 
        iter = 8000,
        warmup = 1000,
        chains = 4,
        cores = 2)
```


```{r}
summary(fit8)
```


rtpj with social anxiety
```{r}
fit9 <- brm_multiple(
        deconMeanCor ~ traitRatings +
                       stateRatings*neuralSimConditionCodes*saTotalC + (1 | dyad), 
        data = rTPJ_data, 
        seed = 111, 
        iter = 8000,
        warmup = 1000,
        chains = 4,
        cores = 2)
```


```{r}
summary(fit9)
```

